# Generated by Django 4.1.2 on 2023-01-09 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('your_menu', '0002_alter_category_options_women'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Women',
            new_name='Food',
        ),
    ]
