# Generated by Django 4.1.2 on 2023-01-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('your_menu', '0003_rename_women_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='content',
            field=models.CharField(max_length=255, null=True, verbose_name='граммы'),
        ),
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.CharField(max_length=255, null=True, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='food',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
    ]
